%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%% Function for Monte Carlo Simulation  %%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%      (01/896410)     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% ----------------------------------------------------------------------- %
%                                                                         %
%                           Introduction                                  %
%         --------------------------------------------------              %
%                                                                         %
%   This function conducts Monte Carlo simulations. The inputs of the     %
%   function are the # of simulations, the number of periods to be        %
%   discarded, and the length of data of interest. The outputs of the     % 
%   function is a data matrix in which every two rows contain the time    %
%   series generated by one simulation.                                   %
%                                                                         %
% ----------------------------------------------------------------------- %

% ----------------------------------------------------------------------- %
%                         Declaration of Variables                        %
%          --------------------------------------------------             %
%                                                                         %
% (1)   M: the number of Monte Carlo simulations                          %
%                                                                         %
% (2)   s: the number of periods to be discarded                          %
%                                                                         %
% (3)   T: length of data                                                 %
%                                                                         %
% (4)   Yrep: bootstrapped time series                                    %
%                                                                         %
% ----------------------------------------------------------------------- %

function [Yrep] = MonteCarlo(M, s, T)

% --------------------------- Initial setup ----------------------------- %

     B = [0.9 , 0 ; 0.5 , 0.5];                                            % Specify the coefficent matrix
     MU = [0 , 0];                                                         % Specify the mean of residuals
     SIGMA = [1 , 0.3; 0.3 , 1];                                           % Specify the covariance of residuals
     Yrep = zeros(2 * M , T + 1 + s);                                      % matrix used to store all replications of time series

% -------------------- Generate the residual matrix --------------------- %

     for j = 1 : M                                                         % M denotes the total number of replications
                                                                           % j denotes the current replication
     U = mvnrnd(MU , SIGMA , T + s)';                                      % generate the current replication of the residuals
     
% ------------- Initialize and generate the time series data ------------ %

     y = zeros(2 , T + 1 + s);                                             % Initialize the current replication of the time series of y
     y(: , 1) = [0 ; 0];                                                   % the initial value of y

         for i = 1 : (T + s)
         y(: , i + 1) = B * y(: , i) + U(: , i);                           % Generate y for each period.
         end

     Yrep((2 * j - 1): (2 * j) , : ) = y;                                  % Store each replication of the time series of y in the matrix Yrep
     end

     Yrep = Yrep(: , s + 1 : end);                                         % Discard the first s observations
